name: Build CardPile Release

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: Build CardPile on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Release
        run: dotnet build -c Release
      - name: Zip Release
        run: Compress-Archive -Path CardPile.App/bin/Release/net8.0/* Windows.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Windows.zip
          draft: true

  build-macos:
    name: Build CardPile on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Release
        run: dotnet build -c Release
      - name: Zip Release
        run: zip macOS.zip CardPile.App/bin/Release/net8.0/* -r
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: macOS.zip
          draft: true